---
- name: Deploy to CloudVision
  hosts: "{{ target_hosts }}"
  gather_facts: false

  tasks:

    - name: Deploy to Static Configuration Studio
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_run_change_control: true
        cv_server: "uzh4-1-8d558e56-eos.topo.testdrive.arista.com"
